In [1]:
import pandas as pd

In [4]:
sales_df = pd.read_csv('clean_csvs/clean_state_purchases_FINAL.csv')

In [5]:
numbers_df = pd.read_csv('clean_csvs/clean_lotto_numbers.csv')

In [6]:
winners_df = pd.read_csv('clean_csvs/clean_winners_by_state.csv')

In [79]:
census_df = pd.read_csv('census2010_2015.csv')

In [80]:
census_df.head()

,Household Income,Median Age,Per Capita Income,Population,Poverty Count,Poverty Rate,Unemployment Count,Unemployment Rate,state,year
0,42081.0,37.5,22984.0,4712651.0,786544.0,16.690054,NaN,NaN,AL,2010
1,66521.0,33.8,30726.0,691189.0,64245.0,9.294853,NaN,NaN,AK,2010
2,50448.0,35.5,25680.0,6246816.0,933113.0,14.937418,NaN,NaN,AZ,2010
3,39267.0,37.2,21274.0,2872684.0,502684.0,17.498757,NaN,NaN,AR,2010
4,60883.0,34.9,29188.0,36637290.0,4919945.0,13.428791,NaN,NaN,CA,2010

In [11]:
del sales_df['date']

In [12]:
sales_df.head()

,draw_sales,jackpot,pp_sales,state_abbr,state_draw_sales,state_pp_sales,date_format,ticket_sales,revenue,year
0,33842134.0,177.0,3144938.0,AR,207040.0,50023.0,2017-12-02,103520.0,257063.0,2017
1,33842134.0,177.0,3144938.0,AZ,790702.0,59666.0,2017-12-02,395351.0,850368.0,2017
2,33842134.0,177.0,3144938.0,CA,3292686.0,0.0,2017-12-02,1646343.0,3292686.0,2017
3,33842134.0,177.0,3144938.0,CO,560076.0,126852.0,2017-12-02,280038.0,686928.0,2017
4,33842134.0,177.0,3144938.0,DC,80140.0,6985.0,2017-12-02,40070.0,87125.0,2017

In [18]:
len(sales_df)

36139

In [9]:
numbers_df.head()

                          numbers  powerball date_format
0  ['24', '26', '28', '59', '63']         16  2017-11-29
1   ['8', '13', '27', '53', '54']          4  2017-11-25
2  ['35', '37', '46', '51', '61']         13  2017-11-22
3  ['17', '28', '31', '32', '39']         26  2017-11-18
4  ['23', '32', '44', '48', '50']         25  2017-11-15

In [19]:
len(numbers_df)

817

In [20]:
merge1 = sales_df.merge(numbers_df, on = 'date_format', how = 'outer')

In [21]:
len(merge1)

36148

In [35]:
merge1[merge1.isnull().any(axis=1)]

,draw_sales,jackpot,pp_sales,state_abbr,state_draw_sales,state_pp_sales,date_format,ticket_sales,revenue,year,numbers,powerball
0,33842134.0,177.0,3144938.0,AR,207040.0,50023.0,2017-12-02,103520.0,257063.0,2017.0,NaN,NaN
1,33842134.0,177.0,3144938.0,AZ,790702.0,59666.0,2017-12-02,395351.0,850368.0,2017.0,NaN,NaN
2,33842134.0,177.0,3144938.0,CA,3292686.0,0.0,2017-12-02,1646343.0,3292686.0,2017.0,NaN,NaN
3,33842134.0,177.0,3144938.0,CO,560076.0,126852.0,2017-12-02,280038.0,686928.0,2017.0,NaN,NaN
4,33842134.0,177.0,3144938.0,DC,80140.0,6985.0,2017-12-02,40070.0,87125.0,2017.0,NaN,NaN
5,33842134.0,177.0,3144938.0,DE,166354.0,12954.0,2017-12-02,83177.0,179308.0,2017.0,NaN,NaN
6,33842134.0,177.0,3144938.0,FL,3222110.0,377607.0,2017-12-02,1611055.0,3599717.0,2017.0,NaN,NaN
7,33842134.0,177.0,3144938.0,GA,1041772.0,57311.0,2017-12-02,520886.0,1099083.0,2017.0,NaN,NaN
8,33842134.0,177.0,3144938.0,IA,385304.0,57613.0,2017-12-02,192652.0,442917.0,2017.0,NaN,NaN
9,33842134.0,177.0,3144938.0,ID,221306.0,24927.0,2017-12-02,110653.0,246233.0,2017.0,NaN,NaN
10,33842134.0,177.0,3144938.0,IL,1022564.0,81137.0,2017-12-02,511282.0,1103701.0,2017.0,NaN,NaN
11,33842134.0,177.0,3144938.0,IN,741664.0,68947.0,2017-12-02,370832.0,810611.0,2017.0,NaN,NaN
12,33842134.0,177.0,3144938.0,KS,302420.0,21391.0,2017-12-02,151210.0,323811.0,2017.0,NaN,NaN
13,33842134.0,177.0,3144938.0,KY,583426.0,40966.0,2017-12-02,291713.0,624392.0,2017.0,NaN,NaN
14,33842134.0,177.0,3144938.0,LA,680204.0,85442.0,2017-12-02,340102.0,765646.0,2017.0,NaN,NaN
15,33842134.0,177.0,3144938.0,MA,839336.0,47288.0,2017-12-02,419668.0,886624.0,2017.0,NaN,NaN
16,33842134.0,177.0,3144938.0,MD,722590.0,47763.0,2017-12-02,361295.0,770353.0,2017.0,NaN,NaN
17,33842134.0,177.0,3144938.0,ME,149902.0,37515.0,2017-12-02,74951.0,187417.0,2017.0,NaN,NaN
18,33842134.0,177.0,3144938.0,MI,1028652.0,55478.0,2017-12-02,514326.0,1084130.0,2017.0,NaN,NaN
19,33842134.0,177.0,3144938.0,MN,520530.0,21335.0,2017-12-02,260265.0,541865.0,2017.0,NaN,NaN
20,33842134.0,177.0,3144938.0,MO,760712.0,30628.0,2017-12-02,380356.0,791340.0,2017.0,NaN,NaN
21,33842134.0,177.0,3144938.0,MT,84252.0,15728.0,2017-12-02,42126.0,99980.0,2017.0,NaN,NaN
22,33842134.0,177.0,3144938.0,NC,1172230.0,160987.0,2017-12-02,586115.0,1333217.0,2017.0,NaN,NaN
23,33842134.0,177.0,3144938.0,ND,77902.0,20328.0,2017-12-02,38951.0,98230.0,2017.0,NaN,NaN
24,33842134.0,177.0,3144938.0,NE,287150.0,22106.0,2017-12-02,143575.0,309256.0,2017.0,NaN,NaN
25,33842134.0,177.0,3144938.0,NH,248514.0,18584.0,2017-12-02,124257.0,267098.0,2017.0,NaN,NaN
26,33842134.0,177.0,3144938.0,NJ,1507958.0,87164.0,2017-12-02,753979.0,1595122.0,2017.0,NaN,NaN
27,33842134.0,177.0,3144938.0,NM,198596.0,27566.0,2017-12-02,99298.0,226162.0,2017.0,NaN,NaN
28,33842134.0,177.0,3144938.0,NY,2709238.0,111981.0,2017-12-02,1354619.0,2821219.0,2017.0,NaN,NaN
29,33842134.0,177.0,3144938.0,OH,890904.0,97021.0,2017-12-02,445452.0,987925.0,2017.0,NaN,NaN
30,33842134.0,177.0,3144938.0,OK,311726.0,73047.0,2017-12-02,155863.0,384773.0,2017.0,NaN,NaN
31,33842134.0,177.0,3144938.0,OR,451908.0,37126.0,2017-12-02,225954.0,489034.0,2017.0,NaN,NaN
32,33842134.0,177.0,3144938.0,PA,1726338.0,204973.0,2017-12-02,863169.0,1931311.0,2017.0,NaN,NaN
33,33842134.0,177.0,3144938.0,PR,26.0,2.0,2017-12-02,13.0,28.0,2017.0,NaN,NaN
34,33842134.0,177.0,3144938.0,RI,211512.0,25325.0,2017-12-02,105756.0,236837.0,2017.0,NaN,NaN
35,33842134.0,177.0,3144938.0,SC,596980.0,135032.0,2017-12-02,298490.0,732012.0,2017.0,NaN,NaN
36,33842134.0,177.0,3144938.0,SD,100286.0,14120.0,2017-12-02,50143.0,114406.0,2017.0,NaN,NaN
37,33842134.0,177.0,3144938.0,TX,2266606.0,342095.0,2017-12-02,1133303.0,2608701.0,2017.0,NaN,NaN
38,33842134.0,177.0,3144938.0,VA,855138.0,84130.0,2017-12-02,427569.0,939268.0,2017.0,NaN,NaN
39,33842134.0,177.0,3144938.0,VI,0.0,0.0,2017-12-02,0.0,0.0,2017.0,NaN,NaN
40,33842134.0,177.0,3144938.0,VT,64168.0,14454.0,2017-12-02,32084.0,78622.0,2017.0,NaN,NaN
41,33842134.0,177.0,3144938.0,WA,469596.0,32410.0,2017-12-02,234798.0,502006.0,2017.0,NaN,NaN
42,33842134.0,177.0,3144938.0,WI,643284.0,53359.0,2017-12-02,321642.0,696643.0,2017.0,NaN,NaN
43,33842134.0,177.0,3144938.0,WV,261384.0,21930.0,2017-12-02,130692.0,283314.0,2017.0,NaN,NaN
44,33842134.0,177.0,3144938.0,WY,63486.0,13552.0,2017-12-02,31743.0,77038.0,2017.0,NaN,NaN

In [33]:
merge1 = merge1[merge1['draw_sales'].notnull()]

In [36]:
len(merge1)

36139

In [49]:
merge2 = merge1.merge(winners_df, on = ["date_format", "state_abbr"], how = 'outer' )

In [50]:
merge2.head()

,draw_sales,jackpot,pp_sales,state_abbr,state_draw_sales,state_pp_sales,date_format,ticket_sales,revenue,year,...,4_PB PP,5 PB,5 PP,5_PB PB,PB_Only PB,PB_Only PP,pb_winners,pp_winners,states,total_winners
0,33842134.0,177.0,3144938.0,AR,207040.0,50023.0,2017-12-02,103520.0,257063.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33842134.0,177.0,3144938.0,AZ,790702.0,59666.0,2017-12-02,395351.0,850368.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,33842134.0,177.0,3144938.0,CA,3292686.0,0.0,2017-12-02,1646343.0,3292686.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,33842134.0,177.0,3144938.0,CO,560076.0,126852.0,2017-12-02,280038.0,686928.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,33842134.0,177.0,3144938.0,DC,80140.0,6985.0,2017-12-02,40070.0,87125.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [68]:
len(merge2)

36139

In [52]:
merge2[merge2.isnull().any(axis=1)]

,draw_sales,jackpot,pp_sales,state_abbr,state_draw_sales,state_pp_sales,date_format,ticket_sales,revenue,year,...,4_PB PP,5 PB,5 PP,5_PB PB,PB_Only PB,PB_Only PP,pb_winners,pp_winners,states,total_winners
0,33842134.0,177.0,3144938.0,AR,207040.0,50023.0,2017-12-02,103520.0,257063.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33842134.0,177.0,3144938.0,AZ,790702.0,59666.0,2017-12-02,395351.0,850368.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,33842134.0,177.0,3144938.0,CA,3292686.0,0.0,2017-12-02,1646343.0,3292686.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,33842134.0,177.0,3144938.0,CO,560076.0,126852.0,2017-12-02,280038.0,686928.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,33842134.0,177.0,3144938.0,DC,80140.0,6985.0,2017-12-02,40070.0,87125.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,33842134.0,177.0,3144938.0,DE,166354.0,12954.0,2017-12-02,83177.0,179308.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,33842134.0,177.0,3144938.0,FL,3222110.0,377607.0,2017-12-02,1611055.0,3599717.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,33842134.0,177.0,3144938.0,GA,1041772.0,57311.0,2017-12-02,520886.0,1099083.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,33842134.0,177.0,3144938.0,IA,385304.0,57613.0,2017-12-02,192652.0,442917.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,33842134.0,177.0,3144938.0,ID,221306.0,24927.0,2017-12-02,110653.0,246233.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,33842134.0,177.0,3144938.0,IL,1022564.0,81137.0,2017-12-02,511282.0,1103701.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,33842134.0,177.0,3144938.0,IN,741664.0,68947.0,2017-12-02,370832.0,810611.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,33842134.0,177.0,3144938.0,KS,302420.0,21391.0,2017-12-02,151210.0,323811.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,33842134.0,177.0,3144938.0,KY,583426.0,40966.0,2017-12-02,291713.0,624392.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,33842134.0,177.0,3144938.0,LA,680204.0,85442.0,2017-12-02,340102.0,765646.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,33842134.0,177.0,3144938.0,MA,839336.0,47288.0,2017-12-02,419668.0,886624.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,33842134.0,177.0,3144938.0,MD,722590.0,47763.0,2017-12-02,361295.0,770353.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,33842134.0,177.0,3144938.0,ME,149902.0,37515.0,2017-12-02,74951.0,187417.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,33842134.0,177.0,3144938.0,MI,1028652.0,55478.0,2017-12-02,514326.0,1084130.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,33842134.0,177.0,3144938.0,MN,520530.0,21335.0,2017-12-02,260265.0,541865.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,33842134.0,177.0,3144938.0,MO,760712.0,30628.0,2017-12-02,380356.0,791340.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,33842134.0,177.0,3144938.0,MT,84252.0,15728.0,2017-12-02,42126.0,99980.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,33842134.0,177.0,3144938.0,NC,1172230.0,160987.0,2017-12-02,586115.0,1333217.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,33842134.0,177.0,3144938.0,ND,77902.0,20328.0,2017-12-02,38951.0,98230.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,33842134.0,177.0,3144938.0,NE,287150.0,22106.0,2017-12-02,143575.0,309256.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,33842134.0,177.0,3144938.0,NH,248514.0,18584.0,2017-12-02,124257.0,267098.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,33842134.0,177.0,3144938.0,NJ,1507958.0,87164.0,2017-12-02,753979.0,1595122.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,33842134.0,177.0,3144938.0,NM,198596.0,27566.0,2017-12-02,99298.0,226162.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,33842134.0,177.0,3144938.0,NY,2709238.0,111981.0,2017-12-02,1354619.0,2821219.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,33842134.0,177.0,3144938.0,OH,890904.0,97021.0,2017-12-02,445452.0,987925.0,2017.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37099,NaN,NaN,NaN,KY,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,14696.0,1353.0,25246.0,2356.0,Kentucky,27602.0
37100,NaN,NaN,NaN,LA,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,1.0,0.0,14003.0,2370.0,24149.0,4067.0,Louisiana,28216.0
37101,NaN,NaN,NaN,ME,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,1780.0,1019.0,3059.0,1699.0,Maine,4758.0
37102,NaN,NaN,NaN,MD,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,10391.0,1031.0,18206.0,1809.0,Maryland,20015.0
37103,NaN,NaN,NaN,MA,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,17554.0,1259.0,30496.0,2130.0,Massachusetts,32626.0
37104,NaN,NaN,NaN,MI,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,13687.0,2099.0,24248.0,3643.0,Michigan,27891.0
37105,NaN,NaN,NaN,MN,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,14262.0,874.0,25216.0,1516.0,Minnesota,26732.0
37106,NaN,NaN,NaN,MO,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,16417.0,1200.0,28565.0,2067.0,Missouri,30632.0
37107,NaN,NaN,NaN,MT,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,1710.0,522.0,2995.0,906.0,Montana,3901.0
37108,NaN,NaN,NaN,NE,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,5859.0,706.0,10150.0,1212.0,Nebraska,11362.0
37109,NaN,NaN,NaN,NH,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,4799.0,517.0,8215.0,872.0,New Hampshire,9087.0
37110,NaN,NaN,NaN,NJ,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,27891.0,4459.0,48121.0,7616.0,New Jersey,55737.0
37111,NaN,NaN,NaN,NM,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,5390.0,863.0,9332.0,1517.0,New Mexico,10849.0
37112,NaN,NaN,NaN,NY,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,41139.0,3817.0,71596.0,6588.0,New York,78184.0
37113,NaN,NaN,NaN,NC,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,17394.0,7863.0,30325.0,13861.0,North Carolina,44186.0
37114,NaN,NaN,NaN,ND,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,813.0,534.0,1430.0,939.0,North Dakota,2369.0
37115,NaN,NaN,NaN,OK,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,5585.0,3565.0,9652.0,6202.0,Oklahoma,15854.0
37116,NaN,NaN,NaN,OR,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,6525.0,1394.0,11421.0,2448.0,Oregon,13869.0
37117,NaN,NaN,NaN,PA,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,1.0,1.0,0.0,37167.0,8095.0,64844.0,13967.0,Pennsylvania,78811.0
37118,NaN,NaN,NaN,RI,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,5352.0,829.0,9032.0,1392.0,Rhode Island,10424.0
37119,NaN,NaN,NaN,SC,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,8695.0,5325.0,15131.0,9235.0,South Carolina,24366.0
37120,NaN,NaN,NaN,SD,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,1982.0,342.0,3471.0,604.0,South Dakota,4075.0
37121,NaN,NaN,NaN,TN,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,12840.0,4084.0,22385.0,6944.0,Tennessee,29329.0
37122,NaN,NaN,NaN,TX,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,18811.0,4404.0,32779.0,7610.0,Texas,40389.0
37123,NaN,NaN,NaN,VT,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,839.0,398.0,1448.0,674.0,Vermont,2122.0
37124,NaN,NaN,NaN,VI,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,144.0,254.0,258.0,455.0,Virgin Islands,713.0
37125,NaN,NaN,NaN,VA,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,7753.0,3168.0,13517.0,5449.0,Virginia,18966.0
37126,NaN,NaN,NaN,WA,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,9107.0,707.0,15814.0,1241.0,Washington,17055.0
37127,NaN,NaN,NaN,WV,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,6907.0,573.0,11942.0,1030.0,West Virginia,12972.0
37128,NaN,NaN,NaN,WI,NaN,NaN,2010-02-03,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,11743.0,1280.0,20431.0,2146.0,Wisconsin,22577.0

In [53]:
merge2 = merge2[merge2['draw_sales'].notnull()]

In [55]:
len(merge2)

36139

In [82]:
census_df.rename(columns = {"state": "state_abbr"}, inplace=True)

In [83]:
merge3 = merge2.merge(census_df, on = ['year', 'state_abbr'], how = "left")

In [84]:
len(merge3)

36139

In [85]:
merge3[merge3.isnull().any(axis=1)]

,draw_sales,jackpot,pp_sales,state_abbr,state_draw_sales,state_pp_sales,date_format,ticket_sales,revenue,year,...,states,total_winners,Household Income,Median Age,Per Capita Income,Population,Poverty Count,Poverty Rate,Unemployment Count,Unemployment Rate
0,33842134.0,177.0,3144938.0,AR,207040.0,50023.0,2017-12-02,103520.0,257063.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,33842134.0,177.0,3144938.0,AZ,790702.0,59666.0,2017-12-02,395351.0,850368.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,33842134.0,177.0,3144938.0,CA,3292686.0,0.0,2017-12-02,1646343.0,3292686.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,33842134.0,177.0,3144938.0,CO,560076.0,126852.0,2017-12-02,280038.0,686928.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,33842134.0,177.0,3144938.0,DC,80140.0,6985.0,2017-12-02,40070.0,87125.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,33842134.0,177.0,3144938.0,DE,166354.0,12954.0,2017-12-02,83177.0,179308.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,33842134.0,177.0,3144938.0,FL,3222110.0,377607.0,2017-12-02,1611055.0,3599717.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,33842134.0,177.0,3144938.0,GA,1041772.0,57311.0,2017-12-02,520886.0,1099083.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,33842134.0,177.0,3144938.0,IA,385304.0,57613.0,2017-12-02,192652.0,442917.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,33842134.0,177.0,3144938.0,ID,221306.0,24927.0,2017-12-02,110653.0,246233.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,33842134.0,177.0,3144938.0,IL,1022564.0,81137.0,2017-12-02,511282.0,1103701.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,33842134.0,177.0,3144938.0,IN,741664.0,68947.0,2017-12-02,370832.0,810611.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,33842134.0,177.0,3144938.0,KS,302420.0,21391.0,2017-12-02,151210.0,323811.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,33842134.0,177.0,3144938.0,KY,583426.0,40966.0,2017-12-02,291713.0,624392.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,33842134.0,177.0,3144938.0,LA,680204.0,85442.0,2017-12-02,340102.0,765646.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,33842134.0,177.0,3144938.0,MA,839336.0,47288.0,2017-12-02,419668.0,886624.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,33842134.0,177.0,3144938.0,MD,722590.0,47763.0,2017-12-02,361295.0,770353.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,33842134.0,177.0,3144938.0,ME,149902.0,37515.0,2017-12-02,74951.0,187417.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,33842134.0,177.0,3144938.0,MI,1028652.0,55478.0,2017-12-02,514326.0,1084130.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,33842134.0,177.0,3144938.0,MN,520530.0,21335.0,2017-12-02,260265.0,541865.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,33842134.0,177.0,3144938.0,MO,760712.0,30628.0,2017-12-02,380356.0,791340.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,33842134.0,177.0,3144938.0,MT,84252.0,15728.0,2017-12-02,42126.0,99980.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,33842134.0,177.0,3144938.0,NC,1172230.0,160987.0,2017-12-02,586115.0,1333217.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,33842134.0,177.0,3144938.0,ND,77902.0,20328.0,2017-12-02,38951.0,98230.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,33842134.0,177.0,3144938.0,NE,287150.0,22106.0,2017-12-02,143575.0,309256.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,33842134.0,177.0,3144938.0,NH,248514.0,18584.0,2017-12-02,124257.0,267098.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,33842134.0,177.0,3144938.0,NJ,1507958.0,87164.0,2017-12-02,753979.0,1595122.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,33842134.0,177.0,3144938.0,NM,198596.0,27566.0,2017-12-02,99298.0,226162.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,33842134.0,177.0,3144938.0,NY,2709238.0,111981.0,2017-12-02,1354619.0,2821219.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,33842134.0,177.0,3144938.0,OH,890904.0,97021.0,2017-12-02,445452.0,987925.0,2017,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36109,37513118.0,144.0,6303025.0,KS,443037.0,31169.0,2010-03-06,443037.0,474206.0,2010,...,Kansas,12492.0,49424.0,36.1,25907.0,2809329.0,338792.0,12.059535,NaN,NaN
36110,37513118.0,144.0,6303025.0,KY,970517.0,80946.0,2010-03-06,970517.0,1051463.0,2010,...,Kentucky,27352.0,41576.0,37.7,22515.0,4285828.0,735782.0,17.167791,NaN,NaN
36111,37513118.0,144.0,6303025.0,LA,1074301.0,150072.0,2010-03-06,1074301.0,1224373.0,2010,...,Louisiana,30377.0,43445.0,35.9,23094.0,4429940.0,780359.0,17.615566,NaN,NaN
36112,37513118.0,144.0,6303025.0,MA,914353.0,80292.0,2010-03-06,914353.0,994645.0,2010,...,Massachusetts,24778.0,64509.0,38.7,33966.0,6477096.0,658391.0,10.164910,NaN,NaN
36113,37513118.0,144.0,6303025.0,MD,677594.0,54823.0,2010-03-06,677594.0,732417.0,2010,...,Maryland,18660.0,70647.0,37.6,34849.0,5696423.0,476732.0,8.368971,NaN,NaN
36114,37513118.0,144.0,6303025.0,ME,188451.0,69451.0,2010-03-06,188451.0,257902.0,2010,...,Maine,5051.0,46933.0,42.0,25385.0,1327665.0,162358.0,12.228838,NaN,NaN
36115,37513118.0,144.0,6303025.0,MI,1096883.0,203231.0,2010-03-06,1096883.0,1300114.0,2010,...,Michigan,30231.0,48432.0,38.1,25135.0,9952687.0,1444004.0,14.508685,NaN,NaN
36116,37513118.0,144.0,6303025.0,MN,936736.0,50241.0,2010-03-06,936736.0,986977.0,2010,...,Minnesota,26272.0,57243.0,37.1,29582.0,5241914.0,542133.0,10.342272,NaN,NaN
36117,37513118.0,144.0,6303025.0,MO,1098912.0,74197.0,2010-03-06,1098912.0,1173109.0,2010,...,Missouri,30737.0,46262.0,37.6,24724.0,5922314.0,802596.0,13.552068,NaN,NaN
36118,37513118.0,144.0,6303025.0,MT,146867.0,33591.0,2010-03-06,146867.0,180458.0,2010,...,Montana,4129.0,43872.0,39.7,23836.0,973739.0,138109.0,14.183369,NaN,NaN
36119,37513118.0,144.0,6303025.0,NC,1584178.0,459696.0,2010-03-06,1584178.0,2043874.0,2010,...,North Carolina,42472.0,45570.0,37.1,24745.0,9271178.0,1399945.0,15.099969,NaN,NaN
36120,37513118.0,144.0,6303025.0,ND,85179.0,33832.0,2010-03-06,85179.0,119011.0,2010,...,North Dakota,2462.0,46781.0,37.2,25803.0,659858.0,78405.0,11.882102,NaN,NaN
36121,37513118.0,144.0,6303025.0,NE,441431.0,46663.0,2010-03-06,441431.0,488094.0,2010,...,Nebraska,12297.0,49342.0,36.2,25229.0,1799125.0,206227.0,11.462628,NaN,NaN
36122,37513118.0,144.0,6303025.0,NH,361010.0,32769.0,2010-03-06,361010.0,393779.0,2010,...,New Hampshire,9615.0,63277.0,40.3,31422.0,1313939.0,99527.0,7.574705,NaN,NaN
36123,37513118.0,144.0,6303025.0,NJ,1565677.0,203024.0,2010-03-06,1565677.0,1768701.0,2010,...,New Jersey,44116.0,69811.0,38.5,34858.0,8721577.0,777968.0,8.920038,NaN,NaN
36124,37513118.0,144.0,6303025.0,NM,383719.0,54719.0,2010-03-06,383719.0,438438.0,2010,...,New Mexico,10836.0,43820.0,36.4,22966.0,2013122.0,361771.0,17.970645,NaN,NaN
36125,37513118.0,144.0,6303025.0,NY,2517663.0,155445.0,2010-03-06,2517663.0,2673108.0,2010,...,New York,71613.0,55603.0,37.7,30948.0,19229752.0,2650166.0,13.781592,NaN,NaN
36126,37513118.0,144.0,6303025.0,OK,604024.0,231666.0,2010-03-06,604024.0,835690.0,2010,...,Oklahoma,16459.0,42979.0,36.3,23094.0,3675339.0,577247.0,15.705953,NaN,NaN
36127,37513118.0,144.0,6303025.0,OR,557447.0,94738.0,2010-03-06,557447.0,652185.0,2010,...,Oregon,15606.0,49260.0,38.1,26171.0,3761925.0,516271.0,13.723586,NaN,NaN
36128,37513118.0,144.0,6303025.0,PA,2900573.0,513460.0,2010-03-06,2900573.0,3414033.0,2010,...,Pennsylvania,81466.0,50398.0,39.8,27049.0,12612705.0,1509858.0,11.970929,NaN,NaN
36129,37513118.0,144.0,6303025.0,RI,401702.0,50315.0,2010-03-06,401702.0,452017.0,2010,...,Rhode Island,11502.0,54902.0,38.9,28707.0,1056389.0,123396.0,11.680924,NaN,NaN
36130,37513118.0,144.0,6303025.0,SC,908233.0,342718.0,2010-03-06,908233.0,1250951.0,2010,...,South Carolina,24380.0,43939.0,37.4,23443.0,4511428.0,716537.0,15.882709,NaN,NaN
36131,37513118.0,144.0,6303025.0,SD,158811.0,21011.0,2010-03-06,158811.0,179822.0,2010,...,South Dakota,4421.0,46369.0,37.2,24110.0,799462.0,105819.0,13.236276,NaN,NaN
36132,37513118.0,144.0,6303025.0,TN,1134766.0,258415.0,2010-03-06,1134766.0,1393181.0,2010,...,Tennessee,30014.0,43314.0,37.6,23722.0,6234968.0,1002467.0,16.078142,NaN,NaN
36133,37513118.0,144.0,6303025.0,TX,903322.0,216572.0,2010-03-06,903322.0,1119894.0,2010,...,Texas,25267.0,49646.0,33.4,24870.0,24311891.0,3972054.0,16.337906,NaN,NaN
36134,37513118.0,144.0,6303025.0,VA,722125.0,166211.0,2010-03-06,722125.0,888336.0,2010,...,Virginia,19652.0,61406.0,37.2,32145.0,7841754.0,781516.0,9.966087,NaN,NaN
36135,37513118.0,144.0,6303025.0,VI,29840.0,18816.0,2010-03-06,29840.0,48656.0,2010,...,Virgin Islands,825.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36136,37513118.0,144.0,6303025.0,VT,78778.0,25085.0,2010-03-06,78778.0,103863.0,2010,...,Vermont,2154.0,51841.0,41.0,27478.0,624258.0,66726.0,10.688850,NaN,NaN
36137,37513118.0,144.0,6303025.0,WA,414727.0,38536.0,2010-03-06,414727.0,453263.0,2010,...,Washington,11695.0,57244.0,37.0,29733.0,6561297.0,780009.0,11.888031,NaN,NaN
36138,37513118.0,144.0,6303025.0,WI,845169.0,81542.0,2010-03-06,845169.0,926711.0,2010,...,Wisconsin,23631.0,51598.0,38.1,26624.0,5637947.0,637613.0,11.309312,NaN,NaN

In [86]:
merge3[['date_format', 'state_abbr']].duplicated().value_counts()

False    36139
dtype: int64

In [87]:
merge3['unique_id'] =merge3['date_format'].astype(str) + "_" + merge3['state_abbr']

In [92]:
merge3[merge3['year'] == 2015]

,draw_sales,jackpot,pp_sales,state_abbr,state_draw_sales,state_pp_sales,date_format,ticket_sales,revenue,year,...,total_winners,Household Income,Median Age,Per Capita Income,Population,Poverty Count,Poverty Rate,Unemployment Count,Unemployment Rate,unique_id
9439,81857312.0,300.0,5760737.0,AR,407008.0,83702.0,2015-12-30,203504.0,490710.0,2015,...,7955.0,41371.0,37.7,22798.0,2958208.0,553644.0,18.715520,104943.0,3.547519,2015-12-30_AR
9440,81857312.0,300.0,5760737.0,AZ,2874896.0,105245.0,2015-12-30,1437448.0,2980141.0,2015,...,57079.0,50255.0,36.8,25848.0,6641928.0,1180690.0,17.776314,275712.0,4.151084,2015-12-30_AZ
9441,81857312.0,300.0,5760737.0,CA,7625142.0,0.0,2015-12-30,3812571.0,7625142.0,2015,...,147070.0,61818.0,35.8,30318.0,38421464.0,6135142.0,15.968007,1891081.0,4.921939,2015-12-30_CA
9442,81857312.0,300.0,5760737.0,CO,1104350.0,218920.0,2015-12-30,552175.0,1323270.0,2015,...,21183.0,60629.0,36.3,32217.0,5278906.0,653969.0,12.388343,195578.0,3.704896,2015-12-30_CO
9443,81857312.0,300.0,5760737.0,CT,1131488.0,148597.0,2015-12-30,565744.0,1280085.0,2015,...,21356.0,70331.0,40.4,38803.0,3593222.0,366351.0,10.195613,172292.0,4.794917,2015-12-30_CT
9444,81857312.0,300.0,5760737.0,DC,153624.0,10577.0,2015-12-30,76812.0,164201.0,2015,...,3007.0,70848.0,33.7,47675.0,647484.0,110365.0,17.045209,35811.0,5.530793,2015-12-30_DC
9445,81857312.0,300.0,5760737.0,DE,434318.0,22842.0,2015-12-30,217159.0,457160.0,2015,...,8516.0,60509.0,39.3,30554.0,926454.0,108315.0,11.691352,36223.0,3.909854,2015-12-30_DE
9446,81857312.0,300.0,5760737.0,FL,6814544.0,631173.0,2015-12-30,3407272.0,7445717.0,2015,...,126442.0,47507.0,41.4,26829.0,19645772.0,3180109.0,16.187244,915976.0,4.662459,2015-12-30_FL
9447,81857312.0,300.0,5760737.0,GA,2484790.0,94286.0,2015-12-30,1242395.0,2579076.0,2015,...,47255.0,49620.0,35.9,25737.0,10006693.0,1788947.0,17.877505,468932.0,4.686184,2015-12-30_GA
9448,81857312.0,300.0,5760737.0,IA,827420.0,97379.0,2015-12-30,413710.0,924799.0,2015,...,16250.0,53183.0,38.1,27950.0,3093526.0,373883.0,12.085982,81735.0,2.642131,2015-12-30_IA
9449,81857312.0,300.0,5760737.0,ID,429264.0,38049.0,2015-12-30,214632.0,467313.0,2015,...,8618.0,47583.0,35.5,23399.0,1616547.0,245177.0,15.166710,55312.0,3.421614,2015-12-30_ID
9450,81857312.0,300.0,5760737.0,IL,2170534.0,120712.0,2015-12-30,1085267.0,2291246.0,2015,...,42387.0,57574.0,37.3,30494.0,12873761.0,1801118.0,13.990612,608516.0,4.726793,2015-12-30_IL
9451,81857312.0,300.0,5760737.0,IN,1779000.0,126760.0,2015-12-30,889500.0,1905760.0,2015,...,35153.0,49255.0,37.3,25346.0,6568645.0,978043.0,14.889570,258739.0,3.939001,2015-12-30_IN
9452,81857312.0,300.0,5760737.0,KS,607150.0,28584.0,2015-12-30,303575.0,635734.0,2015,...,11887.0,52205.0,36.0,27706.0,2892987.0,381353.0,13.181981,88454.0,3.057532,2015-12-30_KS
9453,81857312.0,300.0,5760737.0,KY,1217206.0,65083.0,2015-12-30,608603.0,1282289.0,2015,...,23815.0,43740.0,38.5,24063.0,4397353.0,805841.0,18.325593,174308.0,3.963930,2015-12-30_KY
9454,81857312.0,300.0,5760737.0,LA,1464302.0,130632.0,2015-12-30,732151.0,1594934.0,2015,...,29016.0,45047.0,36.1,24981.0,4625253.0,888280.0,19.205003,178150.0,3.851681,2015-12-30_LA
9455,81857312.0,300.0,5760737.0,MA,2604012.0,90415.0,2015-12-30,1302006.0,2694427.0,2015,...,51137.0,68563.0,39.3,36895.0,6705586.0,748905.0,11.168375,280164.0,4.178069,2015-12-30_MA
9456,81857312.0,300.0,5760737.0,MD,1884704.0,87561.0,2015-12-30,942352.0,1972265.0,2015,...,36117.0,74551.0,38.2,36897.0,5930538.0,576805.0,9.726015,238027.0,4.013582,2015-12-30_MD
9457,81857312.0,300.0,5760737.0,ME,224760.0,47827.0,2015-12-30,112380.0,272587.0,2015,...,4261.0,49331.0,43.8,27655.0,1329100.0,180278.0,13.563915,47497.0,3.573621,2015-12-30_ME
9458,81857312.0,300.0,5760737.0,MI,3717270.0,104618.0,2015-12-30,1858635.0,3821888.0,2015,...,72713.0,49576.0,39.5,26607.0,9900571.0,1616870.0,16.331078,477746.0,4.825439,2015-12-30_MI
9459,81857312.0,300.0,5760737.0,MN,1238036.0,33986.0,2015-12-30,619018.0,1272022.0,2015,...,24655.0,61492.0,37.7,32157.0,5419171.0,596662.0,11.010208,167764.0,3.095750,2015-12-30_MN
9460,81857312.0,300.0,5760737.0,MO,1787242.0,49449.0,2015-12-30,893621.0,1836691.0,2015,...,35267.0,48173.0,38.2,26259.0,6045448.0,915972.0,15.151433,226528.0,3.747084,2015-12-30_MO
9461,81857312.0,300.0,5760737.0,MT,142358.0,22583.0,2015-12-30,71179.0,164941.0,2015,...,2810.0,47169.0,39.7,26381.0,1014699.0,150586.0,14.840460,32361.0,3.189222,2015-12-30_MT
9462,81857312.0,300.0,5760737.0,NC,2597728.0,297968.0,2015-12-30,1298864.0,2895696.0,2015,...,48221.0,46868.0,38.0,25920.0,9845333.0,1667465.0,16.936603,453420.0,4.605431,2015-12-30_NC
9463,81857312.0,300.0,5760737.0,ND,230240.0,53780.0,2015-12-30,115120.0,284020.0,2015,...,4400.0,57181.0,35.4,32035.0,721640.0,79758.0,11.052325,11464.0,1.588604,2015-12-30_ND
9464,81857312.0,300.0,5760737.0,NE,656150.0,42905.0,2015-12-30,328075.0,699055.0,2015,...,12823.0,52997.0,36.2,27882.0,1869365.0,231115.0,12.363289,47602.0,2.546426,2015-12-30_NE
9465,81857312.0,300.0,5760737.0,NH,566758.0,31247.0,2015-12-30,283379.0,598005.0,2015,...,10880.0,66779.0,42.2,34362.0,1324201.0,113840.0,8.596882,42733.0,3.227078,2015-12-30_NH
9466,81857312.0,300.0,5760737.0,NJ,4294028.0,152220.0,2015-12-30,2147014.0,4446248.0,2015,...,83854.0,72093.0,39.4,36582.0,8904413.0,944847.0,10.610997,413343.0,4.642002,2015-12-30_NJ
9467,81857312.0,300.0,5760737.0,NM,406406.0,41884.0,2015-12-30,203203.0,448290.0,2015,...,7893.0,44963.0,37.0,24012.0,2084117.0,429361.0,20.601579,88924.0,4.266747,2015-12-30_NM
9468,81857312.0,300.0,5760737.0,NY,7838702.0,194661.0,2015-12-30,3919351.0,8033363.0,2015,...,149170.0,59269.0,38.1,33236.0,19673174.0,3005943.0,15.279400,829141.0,4.214577,2015-12-30_NY
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14243,32024614.0,131.0,2943548.0,LA,706722.0,75490.0,2015-01-03,353361.0,782212.0,2015,...,10563.0,45047.0,36.1,24981.0,4625253.0,888280.0,19.205003,178150.0,3.851681,2015-01-03_LA
14244,32024614.0,131.0,2943548.0,MA,780688.0,40725.0,2015-01-03,390344.0,821413.0,2015,...,12044.0,68563.0,39.3,36895.0,6705586.0,748905.0,11.168375,280164.0,4.178069,2015-01-03_MA
14245,32024614.0,131.0,2943548.0,MD,707664.0,44275.0,2015-01-03,353832.0,751939.0,2015,...,11146.0,74551.0,38.2,36897.0,5930538.0,576805.0,9.726015,238027.0,4.013582,2015-01-03_MD
14246,32024614.0,131.0,2943548.0,ME,149916.0,34216.0,2015-01-03,74958.0,184132.0,2015,...,2387.0,49331.0,43.8,27655.0,1329100.0,180278.0,13.563915,47497.0,3.573621,2015-01-03_ME
14247,32024614.0,131.0,2943548.0,MI,867468.0,44894.0,2015-01-03,433734.0,912362.0,2015,...,13300.0,49576.0,39.5,26607.0,9900571.0,1616870.0,16.331078,477746.0,4.825439,2015-01-03_MI
14248,32024614.0,131.0,2943548.0,MN,561072.0,20441.0,2015-01-03,280536.0,581513.0,2015,...,8683.0,61492.0,37.7,32157.0,5419171.0,596662.0,11.010208,167764.0,3.095750,2015-01-03_MN
14249,32024614.0,131.0,2943548.0,MO,706592.0,26729.0,2015-01-03,353296.0,733321.0,2015,...,10675.0,48173.0,38.2,26259.0,6045448.0,915972.0,15.151433,226528.0,3.747084,2015-01-03_MO
14250,32024614.0,131.0,2943548.0,MT,86854.0,14929.0,2015-01-03,43427.0,101783.0,2015,...,1375.0,47169.0,39.7,26381.0,1014699.0,150586.0,14.840460,32361.0,3.189222,2015-01-03_MT
14251,32024614.0,131.0,2943548.0,NC,1017924.0,140246.0,2015-01-03,508962.0,1158170.0,2015,...,15924.0,46868.0,38.0,25920.0,9845333.0,1667465.0,16.936603,453420.0,4.605431,2015-01-03_NC
14252,32024614.0,131.0,2943548.0,ND,78440.0,18802.0,2015-01-03,39220.0,97242.0,2015,...,1172.0,57181.0,35.4,32035.0,721640.0,79758.0,11.052325,11464.0,1.588604,2015-01-03_ND
14253,32024614.0,131.0,2943548.0,NE,312836.0,22884.0,2015-01-03,156418.0,335720.0,2015,...,4841.0,52997.0,36.2,27882.0,1869365.0,231115.0,12.363289,47602.0,2.546426,2015-01-03_NE
14254,32024614.0,131.0,2943548.0,NH,249906.0,17043.0,2015-01-03,124953.0,266949.0,2015,...,3872.0,66779.0,42.2,34362.0,1324201.0,113840.0,8.596882,42733.0,3.227078,2015-01-03_NH
14255,32024614.0,131.0,2943548.0,NJ,1196004.0,62513.0,2015-01-03,598002.0,1258517.0,2015,...,18285.0,72093.0,39.4,36582.0,8904413.0,944847.0,10.610997,413343.0,4.642002,2015-01-03_NJ
14256,32024614.0,131.0,2943548.0,NM,225104.0,24961.0,2015-01-03,112552.0,250065.0,2015,...,3397.0,44963.0,37.0,24012.0,2084117.0,429361.0,20.601579,88924.0,4.266747,2015-01-03_NM
14257,32024614.0,131.0,2943548.0,NY,2231892.0,82854.0,2015-01-03,1115946.0,2314746.0,2015,...,34495.0,59269.0,38.1,33236.0,19673174.0,3005943.0,15.279400,829141.0,4.214577,2015-01-03_NY
14258,32024614.0,131.0,2943548.0,OH,774006.0,85188.0,2015-01-03,387003.0,859194.0,2015,...,12063.0,49429.0,39.2,26953.0,11575977.0,1775836.0,15.340701,477251.0,4.122771,2015-01-03_OH
14259,32024614.0,131.0,2943548.0,OK,376094.0,86500.0,2015-01-03,188047.0,462594.0,2015,...,5850.0,46879.0,36.2,25032.0,3849733.0,624043.0,16.210033,115978.0,3.012625,2015-01-03_OK
14260,32024614.0,131.0,2943548.0,OR,299842.0,34483.0,2015-01-03,149921.0,334325.0,2015,...,4573.0,51243.0,39.1,27684.0,3939233.0,636947.0,16.169315,184016.0,4.671366,2015-01-03_OR
14261,32024614.0,131.0,2943548.0,PA,1802414.0,206105.0,2015-01-03,901207.0,2008519.0,2015,...,28946.0,53599.0,40.5,29291.0,12779559.0,1666569.0,13.040896,514993.0,4.029818,2015-01-03_PA
14262,32024614.0,131.0,2943548.0,PR,487408.0,191346.0,2015-01-03,243704.0,678754.0,2015,...,8378.0,19350.0,38.7,11394.0,3583073.0,1616117.0,45.104216,235772.0,6.580162,2015-01-03_PR
14263,32024614.0,131.0,2943548.0,RI,220662.0,24196.0,2015-01-03,110331.0,244858.0,2015,...,3275.0,56852.0,39.7,31118.0,1053661.0,144223.0,13.687799,48418.0,4.595216,2015-01-03_RI
14264,32024614.0,131.0,2943548.0,SC,647306.0,138761.0,2015-01-03,323653.0,786067.0,2015,...,10362.0,45483.0,38.6,24604.0,4777576.0,830901.0,17.391686,217977.0,4.562502,2015-01-03_SC
14265,32024614.0,131.0,2943548.0,SD,106080.0,12498.0,2015-01-03,53040.0,118578.0,2015,...,1646.0,50957.0,36.8,26747.0,843190.0,114907.0,13.627652,20220.0,2.398036,2015-01-03_SD
14266,32024614.0,131.0,2943548.0,TN,728608.0,108125.0,2015-01-03,364304.0,836733.0,2015,...,11387.0,45219.0,38.4,25227.0,6499615.0,1117594.0,17.194772,266297.0,4.097120,2015-01-03_TN
14267,32024614.0,131.0,2943548.0,TX,1798084.0,237543.0,2015-01-03,899042.0,2035627.0,2015,...,28265.0,53207.0,34.1,26999.0,26538614.0,4472451.0,16.852617,912068.0,3.436758,2015-01-03_TX
14268,32024614.0,131.0,2943548.0,VA,756402.0,62995.0,2015-01-03,378201.0,819397.0,2015,...,11909.0,65015.0,37.6,34152.0,8256630.0,921822.0,11.164628,276030.0,3.343132,2015-01-03_VA
14269,32024614.0,131.0,2943548.0,VI,15486.0,5172.0,2015-01-03,7743.0,20658.0,2015,...,216.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2015-01-03_VI
14270,32024614.0,131.0,2943548.0,VT,66086.0,13535.0,2015-01-03,33043.0,79621.0,2015,...,1050.0,55176.0,42.4,29894.0,626604.0,69233.0,11.048924,18957.0,3.025356,2015-01-03_VT
14271,32024614.0,131.0,2943548.0,WA,379850.0,23906.0,2015-01-03,189925.0,403756.0,2015,...,5858.0,61062.0,37.4,31762.0,6985464.0,908512.0,13.005750,277806.0,3.976915,2015-01-03_WA
14272,32024614.0,131.0,2943548.0,WI,552266.0,43151.0,2015-01-03,276133.0,595417.0,2015,...,8457.0,53357.0,39.0,28340.0,5742117.0,724348.0,12.614651,193763.0,3.374417,2015-01-03_WI

In [93]:
merge3.to_csv('final.csv', index = False)